# Generated by Django 2.2.4 on 2019-12-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('body', models.CharField(max_length=5000, null=True)),
                ('image', models.ImageField(null=True, upload_to='post/images')),
                ('category', models.CharField(choices=[('entertainment', 'ENTERTAINMENT'), ('sports', 'SPORTS'), ('travel', 'TRAVEL'), ('personal_life', 'PERSONAL_LIFE'), ('health', 'HEALTH')], default='entertainment', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
