# Generated by Django 2.2.4 on 2019-12-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
