# Generated by Django 2.2.4 on 2020-01-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_like_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('comment', models.TextField(max_length=1000, null=True)),
                ('user', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
