# Generated by Django 2.2.4 on 2020-01-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200101_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('entertainment', 'ENTERTAINMENT'), ('sports', 'SPORTS'), ('travel', 'TRAVEL'), ('personal_life', 'PERSONAL_LIFE'), ('health', 'HEALTH')], max_length=100),
        ),
    ]
