# Generated by Django 2.2.4 on 2020-01-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200102_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('entertainment', 'ENTERTAINMENT'), ('sports', 'SPORTS'), ('travel', 'TRAVEL'), ('personal_life', 'PERSONAL_LIFE'), ('health', 'HEALTH')], default='entertainment', max_length=100),
        ),
    ]
